--
-- Generated from tag.lt
--
return {Stmt = {
    Expr = "Expr"
    , Local = "Local"
    , Let = "Let"
    , Assign = "Assign"
    , Do = "Do"
    , If = "If"
    , Forin = "Forin"
    , Fornum = "Fornum"
    , While = "While"
    , Repeat = "Repeat"
    , Return = "Return"
    , Break = "Break"
    , Goto = "Goto"
    , Label = "Label"
}, Expr = {
    Nil = "Nil"
    , Vararg = "Vararg"
    , Id = "Id"
    , Bool = "Bool"
    , Number = "Number"
    , String = "String"
    , Function = "Function"
    , Table = "Table"
    , Index = "Index"
    , Field = "Field"
    , Invoke = "Invoke"
    , Call = "Call"
    , Unary = "Unary"
    , Binary = "Binary"
}, Type = {
    New = "New"
    , Nil = "Nil"
    , Val = "Val"
    , Tuple = "Tuple"
    , Func = "Func"
    , Tbl = "Tbl"
    , Or = "Or"
    , And = "And"
    , Neg = "Neg"
    , Top = "Top"
    , Bot = "Bot"
    , Mu = "Mu"
}}
